variable "vpc_cidr_block" {}
variable "env" {}
variable "tags" {}
variable "public_subnets" {}
variable "web_subnets" {}
variable "app_subnets" {}
variable "db_subnets" {}
variable "azs" {}
variable "default_vpc_id" {}
variable "default_route_table_id" {}
variable "account_id" {}
variable "rds_allocated_storage" {}
variable "rds_engine" {}
variable "rds_engine_version" {}
variable "rds_instance_class" {}
variable "default_vpc_cidr" {}
